### ISSUE TITLE
Ol3 v3.7.0 - problems with tileUrlFunction

### ISSUE THREAD

**Issue by bogdanvaduva** [schivei/openlayers3-google-tile#1]
I had problems with tileUrlFunction after the release of OL3 -v3.7.0
I made the following changes:
-   return new ol.source.XYZ({
-      projection: options.projection,
-      crossOrigin: null,
-      tileUrlFunction: function(coord) {
-        var x, y, z;
-        if (!coord) {
-          return '';
-        }
-        z = coord[0];
-        x = coord[1];
-        y = coord[2];
-        return "http://mt.google.com/vt/lyrs=" + type + "&x=" + x + "&y=" + y + "&z=" + z;
-      },
-      tileGrid: new ol.tilegrid.TileGrid({
-        origin: options.origin,
-        resolutions: options.resolutions
-      })
-    });
-    return new ol.source.XYZ({
-        url: 'http://mt.google.com/vt/lyrs=' + type + '&x={x}&y={y}&z={z}'
-   });

**Comment by tudorbarascu** [comment]
Shouldn't this go into a pull request as it fixes the latest OL3 problems?
Nice

**Comment by schivei** [comment]
Yep, you can send me a pull request?

**Comment by schivei** [comment]
Solved
